export const assetKeys = ["cash", "investments", "retirement", "property", "vehicles", "otherAssets"];
export const debtKeys = ["homeLoan", "vehicleLoan", "cards", "otherDebt"];

export const defaultProfile = {
  name: "",
  dateOfBirth: "",
  sex: "",
  profession: "",
};

export const defaultValues = {
  cash: 40000,
  investments: 90000,
  retirement: 120000,
  property: 220000,
  vehicles: 25000,
  otherAssets: 5000,
  homeLoan: 120000,
  vehicleLoan: 40000,
  cards: 5000,
  otherDebt: 15000,
  monthlyExpenses: 5000,
};

export const defaultRetirement = {
  currentAge: 53,
  retirementAge: 60,
  retirementAccessAge: 55,
  planToAge: 90,
  cashSavings: 40000,
  investmentSavings: 90000,
  retirementSavings: 120000,
  preRetirementIncome: 9000,
  preRetirementExpenses: 5000,
  monthlySavings: 1000,
  monthlyContribution: 3000,
  retirementContributionSource: "income",
  cashReturn: 3.0,
  investmentReturn: 7.0,
  retirementReturn: 5.5,
  inflation: 2.75,
  monthlySpending: 6000,
  monthlyIncome: 1500,
  moneyEvents: [],
  majorWithdrawals: [],
};

export const scenarios = [
  {
    id: "balanced",
    values: { ...defaultValues },
  },
  {
    id: "starting",
    values: { cash: 18000, investments: 12000, retirement: 45000, property: 0, vehicles: 30000, otherAssets: 5000, homeLoan: 0, vehicleLoan: 50000, cards: 9000, otherDebt: 16000, monthlyExpenses: 3500 },
  },
  {
    id: "growing",
    values: { cash: 120000, investments: 280000, retirement: 310000, property: 420000, vehicles: 50000, otherAssets: 20000, homeLoan: 230000, vehicleLoan: 35000, cards: 0, otherDebt: 0, monthlyExpenses: 6500 },
  },
  {
    id: "freedom",
    values: { cash: 360000, investments: 1050000, retirement: 780000, property: 650000, vehicles: 100000, otherAssets: 60000, homeLoan: 0, vehicleLoan: 0, cards: 0, otherDebt: 0, monthlyExpenses: 8000 },
  },
  {
    id: "insolvent",
    values: { cash: 5000, investments: 10000, retirement: 25000, property: 0, vehicles: 15000, otherAssets: 5000, homeLoan: 0, vehicleLoan: 60000, cards: 25000, otherDebt: 15000, monthlyExpenses: 3000 },
  },
];

const en = {
  brand: "Balance Sheet Square",
  shortBrand: "BSS",
  eyebrow: "PERSONAL WEALTH BLUEPRINT",
  titleA: "See your wealth.",
  titleB: "Shape your freedom.",
  intro: "One clear place to understand what you own, what you owe, and whether your retirement plan is on track.",
  local: "Your figures stay on this device",
  offline: "Works offline",
  saved: "Saved automatically",
  home: "Home",
  square: "My Square",
  assetsPage: "Assets",
  debtsPage: "Liabilities",
  retirePage: "Retirement",
  scenariosPage: "Examples",
  reportPage: "Report",
  overview: "Financial overview",
  overviewHint: "Your latest figures at a glance.",
  netWorth: "Net worth",
  totalAssets: "Total Assets",
  totalFunding: "Total Liabilities + Equity",
  liabilities: "Liabilities",
  equity: "Equity",
  debtAsset: "Debt-to-assets",
  equityRatio: "Equity ratio",
  debtEquity: "Debt-to-equity",
  runway: "Cash runway",
  months: "months",
  perMonth: "per month",
  next: "Next",
  back: "Back",
  open: "Open",
  edit: "Edit",
  startSquare: "Build my financial square",
  planRetirement: "Plan my retirement",
  quickActions: "Choose what to work on",
  quickHint: "Each section is now a focused page with larger controls and clearer results.",
  squareTitle: "Your financial square",
  squareHint: "The left side is what you own. The right side shows debt and the wealth that belongs to you.",
  equation: "Assets = Liabilities + Equity",
  balanced: "Balanced",
  insolvent: "Insolvent / bankruptcy risk",
  bankruptcyNote: "Your liabilities exceed your assets. This is a serious warning; legal bankruptcy depends on formal proceedings.",
  liabilitiesExceed: "Liabilities exceed assets by",
  assetMix: "Asset mix",
  assetsTitle: "Enter your assets",
  assetsHint: "Use realistic current values, not original purchase prices.",
  debtsTitle: "Enter your liabilities",
  debtsHint: "Use the latest outstanding balances for every debt.",
  cash: "Cash & savings",
  investments: "Investments",
  retirement: "Retirement account / EPF / CPF / 401(k)",
  property: "Property",
  vehicles: "Vehicles",
  otherAssets: "Other assets",
  homeLoan: "Home loan",
  vehicleLoan: "Vehicle loan",
  cards: "Credit cards / personal loans",
  otherDebt: "Other liabilities",
  monthlyExpenses: "Monthly living expenses",
  assetTotal: "Asset total",
  debtTotal: "Debt total",
  guideValue: "Guide to value",
  assetGuide: "Cash at bank, market value of investments, withdrawable retirement savings, and realistic resale values.",
  debtGuide: "Include principal still owed. Do not enter the original loan amount if part has already been repaid.",
  retirementTitle: "Retirement simulator",
  retirementHint: "See when you can afford to retire and whether your money can support you afterwards.",
  preRetirement: "Pre-Retirement",
  postRetirement: "Post-Retirement",
  preRetirementHint: "Am I saving enough, and when can I retire?",
  postRetirementHint: "How much can I spend, and how long will my money last?",
  currentAge: "Current age",
  retirementAge: "Preferred retirement age",
  retirementAccessAge: "Retirement fund accessible at age",
  retirementAccessHelp: "The age your locked retirement savings can be used. Enter the rule that applies to your account.",
  planToAge: "Plan until age",
  currentSavings: "Retirement resources",
  monthlySavings: "Monthly personal savings",
  annualSavings: "Yearly personal savings",
  monthlyContribution: "Monthly retirement fund contribution",
  annualRetirementContribution: "Yearly retirement contribution",
  cashReturn: "Cash / savings return",
  investmentReturn: "Investment + dividends return",
  retirementReturn: "Retirement account return",
  inflation: "Annual inflation",
  monthlySpending: "Monthly spending today",
  desiredRetirementSpending: "Desired monthly spending after retirement — today's value",
  maximumMonthlySpending: "Maximum sustainable monthly spending",
  useMaximumSpending: "Use maximum sustainable spending",
  monthlyIncome: "Other monthly retirement income",
  monthlyIncomeHelp: "Rentals, pension, annuity, others.",
  majorWithdrawals: "Major withdrawals & emergencies",
  majorWithdrawalsHelp: "Medical costs, renovation, vehicle purchase or unexpected losses.",
  plannedLargeExpenses: "Planned large expenses",
  plannedLargeExpensesHelp: "Property deposit, car, education or medical costs before retirement. If financed, enter only the cash deposit, fees or amount paid from savings.",
  preRetirementMonthlyIncome: "Monthly income before retirement",
  preRetirementMonthlyExpenses: "Monthly expenses before retirement",
  retirementContributionSource: "Retirement contribution source",
  retirementContributionSourceHelp: "Choose where the contribution comes from. Existing savings is a transfer, not new wealth.",
  contributionSources: ["Monthly income", "External contribution", "Existing savings"],
  availableToSave: "Available to save",
  oneTimeMoneyEvents: "One-time money events",
  oneTimeMoneyEventsHelp: "Add sale proceeds, inheritance, bonuses or other one-time income, and schedule large withdrawals in the same list.",
  noMoneyEvents: "No one-time money events added",
  addMoney: "Add money",
  withdrawMoney: "Withdraw money",
  eventAge: "Age",
  eventMonth: "Month (1–12)",
  netAmountReceived: "Net amount received",
  eventAmount: "Amount",
  eventReason: "Reason",
  eventDestination: "Destination",
  saveMoneyEvent: "Save event",
  freeMoneyEventLimit: "Free version supports one one-time money event. Paid supports multiple events.",
  addMoneyReasons: ["Sell property", "Sell vehicle", "Inheritance or gift", "Bonus or one-time side income", "Business proceeds", "Insurance payment", "Other income"],
  withdrawMoneyReasons: ["Property deposit", "Education expenses", "Medical expenses", "Renovation", "New car", "Family support", "Fraud or scam", "Other emergency"],
  moneyDestinations: ["Cash", "Investments", "Retirement fund"],
  netProceedsNote: "For property or vehicle sales, enter net proceeds after outstanding loans, fees and taxes.",
  moneyAdded: "Money added",
  moneyWithdrawn: "Money withdrawn",
  eventImpact: "One-time event impact",
  withoutEvents: "Without events",
  withEvents: "With events",
  noMajorWithdrawals: "No major withdrawals added",
  addWithdrawal: "Add withdrawal",
  withdrawalAge: "Withdrawal age",
  withdrawalMonth: "Month after birthday",
  withdrawalAmount: "Amount",
  withdrawalReason: "Reason",
  amountAtFutureAge: "Enter the amount expected at that future age.",
  automaticLowestReturn: "Automatic — lowest return first",
  saveWithdrawal: "Save withdrawal",
  cancel: "Cancel",
  withdrawalEdit: "Edit",
  withdrawalRemove: "Remove",
  freeWithdrawalLimit: "Free version supports one major withdrawal. Paid supports multiple withdrawals.",
  withdrawalReasons: ["Medical expenses", "House renovation", "New car", "Fraud or scam loss", "Family support", "Other emergency", "Property deposit", "Education expenses"],
  beforeWithdrawal: "Before withdrawal",
  afterWithdrawal: "After withdrawal",
  withdrawalImpact: "Withdrawal impact",
  unfundedExpense: "Unfunded major expense",
  useMyBalance: "Use my cash + investment + retirement figures",
  projectedFund: "Projected fund at retirement",
  projectedAccessibleFund: "Accessible at retirement",
  projectedLockedFund: "Locked until access age",
  requiredFund: "Estimated fund required",
  targetRetirementSum: "Target retirement sum",
  fundingGap: "Funding gap / surplus",
  earliestRetirementAge: "Earliest possible retirement age",
  financiallyIndependentNow: "You may retire now",
  mayRetireAt: "You may retire as early as age",
  notYetAchievable: "Not yet achievable with these figures",
  bridgePeriod: "Early-retirement bridge",
  bridgePeriodHelp: "Accessible savings must cover spending until the locked retirement fund becomes available.",
  increaseSavingsBy: "Increase monthly savings by",
  requiredMonthlySavings: "Required monthly personal savings",
  yearlyTargets: "Yearly saving targets",
  yearlyTargetsHint: "Compare your projected balance with the amount needed to stay on track.",
  targetBalance: "Target balance",
  accessibleBalance: "Accessible balance",
  lockedBalance: "Locked retirement balance",
  projectedBalance: "Projected balance",
  advancedSettings: "Advanced assumptions",
  lastsUntil: "Fund lasts until",
  fundsMayRunOutAt: "Funds may run out at age",
  remainingFundAtAge: "Remaining fund at age",
  fundsSupportThroughAge: "Funds support you through age",
  age: "Age",
  onTrack: "On track",
  needsWork: "Plan needs adjustment",
  monthlySavingNeeded: "Estimated monthly saving needed",
  firstYearSpend: "First-year retirement spending",
  projection: "Fund projection",
  projectionNote: "Illustration only. Returns and inflation vary, and the simulator does not include tax or investment fees.",
  assumptions: "Assumptions",
  scenariosTitle: "Explore example paths",
  scenariosHint: "Load an example, then adjust the figures to match your own finances.",
  loadScenario: "Use this example",
  scenarioNames: ["Balanced RM500k", "Starting out", "Growing wealth", "Financial freedom", "Insolvency warning"],
  scenarioDescs: ["A 64% equity base", "Build liquidity and reduce debt", "Assets grow faster than debt", "High runway with no debt", "Liabilities exceed all assets"],
  profilePage: "Profile",
  profileTitle: "Your information",
  profileHint: "Add basic details once. Your age will update automatically from your date of birth.",
  fullName: "Full name",
  dateOfBirth: "Date of birth",
  calculatedAge: "Calculated age",
  sex: "Sex",
  profession: "Profession",
  sexChoose: "Choose",
  sexMale: "Male",
  sexFemale: "Female",
  sexPreferNot: "Prefer not to say",
  profileSaved: "Profile saved on this device",
  editProfile: "My profile",
  liabilitiesDetails: "Liabilities details",
  wealthReport: "Wealth Report",
  professionLabel: "Profession",
  asAt: "As at",
  reportTitle: "Your financial report",
  reportHint: "Save a private snapshot or share it with someone you trust.",
  upgradeTitle: "Unlock the full retirement report",
  upgradeMessage: "Upgrade to the Paid version for multiple major withdrawals, custom return assumptions and the full yearly summary.",
  unlockFullVersion: "Unlock Full Version",
  restorePurchase: "Restore purchase",
  billingConnecting: "Connecting to Google Play…",
  billingUnavailable: "Google Play purchase is unavailable. Install or update the app from Google Play and try again.",
  purchaseRestored: "Full Version restored.",
  purchaseCancelled: "Purchase cancelled.",
  purchasePending: "Payment is pending. Full Version will unlock after Google confirms payment.",
  noPurchaseFound: "No previous Full Version purchase was found for this Google account.",
  paidEdition: "Paid version",
  close: "Close",
  conservativeAssumption: "Conservative 2.5% assumption",
  customizeReturns: "Customize return assumptions with the Paid version.",
  quarterlyProgress: "Quarterly progress",
  quarterlyProgressHint: "Save one snapshot each quarter to track assets, liabilities and equity.",
  saveQuarter: "Save this quarter",
  progressLimitFree: "Free version stores up to 2 quarterly snapshots.",
  progressLimitPaid: "Paid version stores up to 40 quarterly snapshots (10 years).",
  snapshotSaved: "Quarter saved",
  noSnapshots: "No quarterly snapshots yet.",
  retirementYearlySummary: "Post-Retirement yearly summary",
  freeYearlyLimit: "Free report shows the first 5 retirement years. Paid shows the full yearly summary.",
  freePreYearlyLimit: "Free report shows the first 5 pre-retirement years. Paid shows the full yearly targets.",
  paidYearlyLimit: "Full yearly summary through the selected final age.",
  openingBalance: "Opening balance",
  cashBalance: "Year-end cash balance",
  investmentBalance: "Year-end investment + dividend balance",
  retirementBalance: "Year-end retirement fund balance",
  yearlySpending: "Yearly spending",
  otherMonthlyIncome: "Other monthly income",
  otherYearlyIncome: "Other yearly income",
  totalReturn: "Total return",
  endingBalance: "Year-end balance",
  exportPdf: "Export PDF",
  shareReport: "Share report",
  exporting: "Preparing your report…",
  pdfReady: "PDF downloaded",
  shared: "Report shared",
  shareUnavailable: "Direct sharing is unavailable, so the PDF was downloaded instead.",
  privacyPolicy: "Privacy policy",
  reportPrivacy: "The report is created on your device. Nothing is uploaded by Balance Sheet Square.",
  reset: "Reset all figures",
  resetConfirm: "Reset the balance sheet and retirement simulator to the original example?",
  strong: "Strong",
  moderate: "Moderate",
  attention: "Needs attention",
  debtFree: "Debt-free",
  custom: "Custom figures",
  percentage: "%",
  currency: "Currency",
};

const ms = {
  brand: "Petak Kunci Kira-kira",
  eyebrow: "PELAN INDUK HARTA PERIBADI",
  titleA: "Lihat harta anda.",
  titleB: "Bentuk kebebasan anda.",
  intro: "Satu tempat yang jelas untuk memahami apa yang anda miliki, hutang anda dan sama ada pelan persaraan berada di landasan.",
  local: "Angka anda kekal pada peranti ini",
  offline: "Berfungsi luar talian",
  saved: "Disimpan secara automatik",
  home: "Utama",
  square: "Petak Saya",
  assetsPage: "Aset",
  debtsPage: "Liabiliti",
  retirePage: "Persaraan",
  scenariosPage: "Contoh",
  reportPage: "Laporan",
  overview: "Gambaran kewangan",
  overviewHint: "Angka terkini anda sepintas lalu.",
  netWorth: "Nilai bersih",
  totalAssets: "Jumlah Aset",
  totalFunding: "Jumlah Liabiliti + Ekuiti",
  liabilities: "Liabiliti",
  equity: "Ekuiti",
  debtAsset: "Hutang kepada aset",
  equityRatio: "Nisbah ekuiti",
  debtEquity: "Hutang kepada ekuiti",
  runway: "Tempoh tunai",
  months: "bulan",
  perMonth: "sebulan",
  next: "Seterusnya",
  back: "Kembali",
  open: "Buka",
  edit: "Ubah",
  startSquare: "Bina petak kewangan saya",
  planRetirement: "Rancang persaraan saya",
  quickActions: "Pilih perkara untuk diurus",
  quickHint: "Setiap bahagian kini mempunyai halaman fokus, kawalan lebih besar dan keputusan lebih jelas.",
  squareTitle: "Petak kewangan anda",
  squareHint: "Bahagian kiri ialah apa yang anda miliki. Bahagian kanan menunjukkan hutang dan harta milik anda.",
  equation: "Aset = Liabiliti + Ekuiti",
  balanced: "Seimbang",
  insolvent: "Tidak solven / risiko muflis",
  bankruptcyNote: "Liabiliti melebihi aset. Ini amaran serius; status muflis bergantung pada proses undang-undang rasmi.",
  liabilitiesExceed: "Liabiliti melebihi aset sebanyak",
  assetMix: "Campuran aset",
  assetsTitle: "Masukkan aset anda",
  assetsHint: "Gunakan nilai semasa yang realistik, bukan harga belian asal.",
  debtsTitle: "Masukkan liabiliti anda",
  debtsHint: "Gunakan baki terkini bagi setiap hutang.",
  cash: "Tunai & simpanan",
  investments: "Pelaburan",
  retirement: "Akaun persaraan / EPF / CPF / 401(k)",
  property: "Hartanah",
  vehicles: "Kenderaan",
  otherAssets: "Aset lain",
  homeLoan: "Pinjaman rumah",
  vehicleLoan: "Pinjaman kenderaan",
  cards: "Kad kredit / pinjaman peribadi",
  otherDebt: "Liabiliti lain",
  monthlyExpenses: "Perbelanjaan hidup bulanan",
  assetTotal: "Jumlah aset",
  debtTotal: "Jumlah hutang",
  guideValue: "Panduan nilai",
  assetGuide: "Tunai di bank, nilai pasaran pelaburan, simpanan persaraan yang boleh dikeluarkan dan nilai jualan semula yang realistik.",
  debtGuide: "Masukkan prinsipal yang masih terhutang. Jangan gunakan jumlah pinjaman asal jika sebahagiannya telah dibayar.",
  retirementTitle: "Simulator persaraan",
  retirementHint: "Lihat bila anda mampu bersara dan sama ada wang mencukupi selepas bersara.",
  preRetirement: "Pra-Persaraan",
  postRetirement: "Pasca-Persaraan",
  preRetirementHint: "Adakah simpanan saya mencukupi, dan bila saya boleh bersara?",
  postRetirementHint: "Berapa banyak boleh dibelanja, dan berapa lama wang akan bertahan?",
  currentAge: "Umur semasa",
  retirementAge: "Umur persaraan pilihan",
  retirementAccessAge: "Dana persaraan boleh digunakan pada umur",
  retirementAccessHelp: "Umur simpanan persaraan terkunci boleh digunakan. Masukkan peraturan akaun anda.",
  planToAge: "Rancang sehingga umur",
  currentSavings: "Sumber persaraan",
  monthlySavings: "Simpanan peribadi bulanan",
  annualSavings: "Simpanan peribadi tahunan",
  monthlyContribution: "Caruman dana persaraan bulanan",
  annualRetirementContribution: "Caruman persaraan tahunan",
  cashReturn: "Pulangan tunai / simpanan",
  investmentReturn: "Pulangan pelaburan + dividen",
  retirementReturn: "Pulangan akaun persaraan",
  inflation: "Inflasi tahunan",
  monthlySpending: "Perbelanjaan bulanan hari ini",
  desiredRetirementSpending: "Perbelanjaan bulanan selepas bersara — nilai hari ini",
  maximumMonthlySpending: "Perbelanjaan bulanan mampan maksimum",
  useMaximumSpending: "Guna perbelanjaan mampan maksimum",
  monthlyIncome: "Pendapatan persaraan bulanan lain",
  monthlyIncomeHelp: "Sewa, pencen, anuiti, lain-lain.",
  majorWithdrawals: "Pengeluaran besar & kecemasan",
  majorWithdrawalsHelp: "Kos perubatan, pengubahsuaian, pembelian kenderaan atau kerugian tidak dijangka.",
  plannedLargeExpenses: "Perbelanjaan besar yang dirancang",
  plannedLargeExpensesHelp: "Deposit hartanah, kereta, pendidikan atau kos perubatan sebelum bersara. Jika dibiayai, masukkan hanya deposit tunai, yuran atau jumlah dibayar daripada simpanan.",
  preRetirementMonthlyIncome: "Pendapatan bulanan sebelum bersara",
  preRetirementMonthlyExpenses: "Perbelanjaan bulanan sebelum bersara",
  retirementContributionSource: "Sumber caruman dana persaraan",
  retirementContributionSourceHelp: "Pilih sumber caruman. Simpanan sedia ada ialah pindahan, bukan kekayaan baharu.",
  contributionSources: ["Pendapatan bulanan", "Caruman luar", "Simpanan sedia ada"],
  availableToSave: "Baki tersedia untuk disimpan",
  oneTimeMoneyEvents: "Peristiwa wang sekali sahaja",
  oneTimeMoneyEventsHelp: "Tambah hasil jualan, pusaka, bonus atau pendapatan sekali sahaja dan jadualkan pengeluaran besar dalam senarai yang sama.",
  noMoneyEvents: "Tiada peristiwa wang sekali sahaja",
  addMoney: "Tambah wang",
  withdrawMoney: "Keluarkan wang",
  eventAge: "Umur",
  eventMonth: "Bulan (1–12)",
  netAmountReceived: "Jumlah bersih diterima",
  eventAmount: "Jumlah",
  eventReason: "Sebab",
  eventDestination: "Destinasi",
  saveMoneyEvent: "Simpan peristiwa",
  freeMoneyEventLimit: "Versi Percuma menyokong satu peristiwa wang sekali sahaja. Versi Berbayar menyokong berbilang peristiwa.",
  addMoneyReasons: ["Jual hartanah", "Jual kenderaan", "Pusaka atau hadiah", "Bonus atau pendapatan sampingan sekali sahaja", "Hasil perniagaan", "Bayaran insurans", "Pendapatan lain"],
  withdrawMoneyReasons: ["Deposit hartanah", "Perbelanjaan pendidikan", "Perbelanjaan perubatan", "Pengubahsuaian", "Kereta baharu", "Sokongan keluarga", "Penipuan atau scam", "Kecemasan lain"],
  moneyDestinations: ["Tunai", "Pelaburan", "Dana persaraan"],
  netProceedsNote: "Untuk jualan hartanah atau kenderaan, masukkan hasil bersih selepas baki pinjaman, yuran dan cukai.",
  moneyAdded: "Wang ditambah",
  moneyWithdrawn: "Wang dikeluarkan",
  eventImpact: "Kesan peristiwa sekali sahaja",
  withoutEvents: "Tanpa peristiwa",
  withEvents: "Dengan peristiwa",
  noMajorWithdrawals: "Tiada pengeluaran besar ditambah",
  addWithdrawal: "Tambah pengeluaran",
  withdrawalAge: "Umur pengeluaran",
  withdrawalMonth: "Bulan selepas hari lahir",
  withdrawalAmount: "Jumlah",
  withdrawalReason: "Sebab",
  amountAtFutureAge: "Masukkan jumlah yang dijangka pada umur masa hadapan itu.",
  automaticLowestReturn: "Automatik — pulangan terendah dahulu",
  saveWithdrawal: "Simpan pengeluaran",
  cancel: "Batal",
  withdrawalEdit: "Sunting",
  withdrawalRemove: "Padam",
  freeWithdrawalLimit: "Versi Percuma menyokong satu pengeluaran besar. Versi Berbayar menyokong berbilang pengeluaran.",
  withdrawalReasons: ["Perbelanjaan perubatan", "Pengubahsuaian rumah", "Kereta baharu", "Kerugian penipuan atau scam", "Sokongan keluarga", "Kecemasan lain", "Deposit hartanah", "Perbelanjaan pendidikan"],
  beforeWithdrawal: "Sebelum pengeluaran",
  afterWithdrawal: "Selepas pengeluaran",
  withdrawalImpact: "Kesan pengeluaran",
  unfundedExpense: "Perbelanjaan besar tidak dibiayai",
  useMyBalance: "Guna angka tunai + pelaburan + persaraan saya",
  projectedFund: "Dana dijangka ketika bersara",
  projectedAccessibleFund: "Boleh digunakan ketika bersara",
  projectedLockedFund: "Terkunci sehingga umur akses",
  requiredFund: "Anggaran dana diperlukan",
  targetRetirementSum: "Sasaran jumlah persaraan",
  fundingGap: "Kekurangan / lebihan dana",
  earliestRetirementAge: "Umur persaraan paling awal",
  financiallyIndependentNow: "Anda mungkin boleh bersara sekarang",
  mayRetireAt: "Anda mungkin boleh bersara seawal umur",
  notYetAchievable: "Belum dapat dicapai dengan angka ini",
  bridgePeriod: "Jambatan persaraan awal",
  bridgePeriodHelp: "Simpanan yang boleh digunakan mesti menampung perbelanjaan sehingga dana persaraan terkunci boleh digunakan.",
  increaseSavingsBy: "Tambah simpanan bulanan sebanyak",
  requiredMonthlySavings: "Simpanan peribadi bulanan diperlukan",
  yearlyTargets: "Sasaran simpanan tahunan",
  yearlyTargetsHint: "Bandingkan baki unjuran dengan jumlah yang diperlukan untuk kekal di landasan.",
  targetBalance: "Baki sasaran",
  accessibleBalance: "Baki boleh digunakan",
  lockedBalance: "Baki persaraan terkunci",
  projectedBalance: "Baki unjuran",
  advancedSettings: "Andaian lanjutan",
  lastsUntil: "Dana bertahan sehingga",
  fundsMayRunOutAt: "Dana mungkin habis pada umur",
  remainingFundAtAge: "Baki dana pada umur",
  fundsSupportThroughAge: "Dana menyokong anda sehingga umur",
  age: "Umur",
  onTrack: "Di landasan",
  needsWork: "Pelan perlu dilaras",
  monthlySavingNeeded: "Anggaran simpanan bulanan diperlukan",
  firstYearSpend: "Perbelanjaan tahun pertama persaraan",
  projection: "Unjuran dana",
  projectionNote: "Ilustrasi sahaja. Pulangan dan inflasi berubah, dan simulasi tidak termasuk cukai atau yuran pelaburan.",
  assumptions: "Andaian",
  scenariosTitle: "Terokai contoh laluan",
  scenariosHint: "Muatkan contoh, kemudian laraskan mengikut kewangan anda.",
  loadScenario: "Guna contoh ini",
  scenarioNames: ["Seimbang RM500k", "Permulaan", "Harta berkembang", "Kebebasan kewangan", "Amaran tidak solven"],
  scenarioDescs: ["Asas ekuiti 64%", "Bina kecairan dan kurangkan hutang", "Aset berkembang lebih pantas", "Tempoh tunai tinggi tanpa hutang", "Liabiliti melebihi semua aset"],
  profilePage: "Profil",
  profileTitle: "Maklumat anda",
  profileHint: "Masukkan maklumat asas sekali. Umur anda akan dikemas kini secara automatik daripada tarikh lahir.",
  fullName: "Nama penuh",
  dateOfBirth: "Tarikh lahir",
  calculatedAge: "Umur dikira",
  sex: "Jantina",
  profession: "Pekerjaan",
  sexChoose: "Pilih",
  sexMale: "Lelaki",
  sexFemale: "Perempuan",
  sexPreferNot: "Tidak mahu nyatakan",
  profileSaved: "Profil disimpan pada peranti ini",
  editProfile: "Profil saya",
  liabilitiesDetails: "Butiran liabiliti",
  wealthReport: "Laporan Harta",
  professionLabel: "Pekerjaan",
  asAt: "Setakat",
  reportTitle: "Laporan kewangan anda",
  reportHint: "Simpan rekod peribadi atau kongsi dengan individu yang anda percayai.",
  upgradeTitle: "Buka laporan persaraan penuh",
  upgradeMessage: "Naik taraf ke versi Berbayar untuk berbilang pengeluaran besar, andaian pulangan tersuai dan ringkasan tahunan penuh.",
  unlockFullVersion: "Buka Versi Penuh",
  restorePurchase: "Pulihkan pembelian",
  billingConnecting: "Menyambung ke Google Play…",
  billingUnavailable: "Pembelian Google Play tidak tersedia. Pasang atau kemas kini aplikasi daripada Google Play dan cuba lagi.",
  purchaseRestored: "Versi Penuh telah dipulihkan.",
  purchaseCancelled: "Pembelian dibatalkan.",
  purchasePending: "Pembayaran sedang diproses. Versi Penuh akan dibuka selepas pengesahan Google.",
  noPurchaseFound: "Tiada pembelian Versi Penuh terdahulu ditemui untuk akaun Google ini.",
  paidEdition: "Versi Berbayar",
  close: "Tutup",
  conservativeAssumption: "Andaian konservatif 2.5%",
  customizeReturns: "Ubah andaian pulangan dengan versi Berbayar.",
  quarterlyProgress: "Kemajuan suku tahunan",
  quarterlyProgressHint: "Simpan satu rekod setiap suku untuk menjejak aset, liabiliti dan ekuiti.",
  saveQuarter: "Simpan suku ini",
  progressLimitFree: "Versi percuma menyimpan sehingga 2 rekod suku tahunan.",
  progressLimitPaid: "Versi Berbayar menyimpan sehingga 40 rekod suku tahunan (10 tahun).",
  snapshotSaved: "Suku disimpan",
  noSnapshots: "Belum ada rekod suku tahunan.",
  retirementYearlySummary: "Ringkasan tahunan pasca-persaraan",
  freeYearlyLimit: "Laporan Percuma menunjukkan 5 tahun persaraan pertama. Versi Berbayar menunjukkan ringkasan penuh.",
  freePreYearlyLimit: "Laporan Percuma menunjukkan 5 tahun pra-persaraan pertama. Versi Berbayar menunjukkan semua sasaran tahunan.",
  paidYearlyLimit: "Ringkasan tahunan penuh sehingga umur akhir yang dipilih.",
  openingBalance: "Baki awal",
  cashBalance: "Baki tunai akhir tahun",
  investmentBalance: "Baki pelaburan + dividen akhir tahun",
  retirementBalance: "Baki dana persaraan akhir tahun",
  yearlySpending: "Perbelanjaan tahunan",
  otherMonthlyIncome: "Pendapatan bulanan lain",
  otherYearlyIncome: "Pendapatan tahunan lain",
  totalReturn: "Jumlah pulangan",
  endingBalance: "Baki akhir tahun",
  exportPdf: "Eksport PDF",
  shareReport: "Kongsi laporan",
  exporting: "Menyediakan laporan anda…",
  pdfReady: "PDF telah dimuat turun",
  shared: "Laporan telah dikongsi",
  shareUnavailable: "Perkongsian terus tidak tersedia, jadi PDF telah dimuat turun.",
  privacyPolicy: "Dasar privasi",
  reportPrivacy: "Laporan dicipta pada peranti anda. Tiada data dimuat naik oleh Petak Kunci Kira-kira.",
  reset: "Tetapkan semula semua angka",
  resetConfirm: "Tetapkan semula petak kewangan dan simulator persaraan kepada contoh asal?",
  strong: "Kukuh",
  moderate: "Sederhana",
  attention: "Perlu perhatian",
  debtFree: "Bebas hutang",
  custom: "Angka tersuai",
  currency: "Mata wang",
};

const zh = {
  brand: "个人资产负债方格",
  eyebrow: "个人财富蓝图",
  titleA: "看见你的财富。",
  titleB: "塑造你的自由。",
  intro: "在一个清晰的空间里，了解你拥有多少、负债多少，以及退休计划是否在正确轨道上。",
  local: "你的数据只保留在此设备",
  offline: "可离线使用",
  saved: "自动保存",
  home: "主页",
  square: "我的方格",
  assetsPage: "资产",
  debtsPage: "负债",
  retirePage: "退休",
  scenariosPage: "示例",
  reportPage: "报告",
  overview: "财务概览",
  overviewHint: "快速查看你的最新数据。",
  netWorth: "净资产",
  totalAssets: "总资产",
  totalFunding: "总负债 + 净资产",
  liabilities: "负债",
  equity: "净资产",
  debtAsset: "负债资产比",
  equityRatio: "净资产比率",
  debtEquity: "负债净资产比",
  runway: "现金可用期",
  months: "个月",
  perMonth: "每月",
  next: "下一步",
  back: "返回",
  open: "打开",
  edit: "修改",
  startSquare: "建立我的财务方格",
  planRetirement: "规划我的退休",
  quickActions: "选择要处理的项目",
  quickHint: "每个部分现在都有独立页面、更大的控件和更清晰的结果。",
  squareTitle: "你的财务方格",
  squareHint: "左边是你拥有的资产；右边显示负债和真正属于你的财富。",
  equation: "资产 = 负债 + 净资产",
  balanced: "平衡",
  insolvent: "资不抵债 / 破产风险",
  bankruptcyNote: "负债已超过资产。这是严重警讯；法律上的破产须经正式程序确定。",
  liabilitiesExceed: "负债超出资产",
  assetMix: "资产组合",
  assetsTitle: "输入你的资产",
  assetsHint: "使用合理的当前价值，而不是原始买入价。",
  debtsTitle: "输入你的负债",
  debtsHint: "使用每项债务最新的未偿余额。",
  cash: "现金与储蓄",
  investments: "投资",
  retirement: "退休账户 / EPF / CPF / 401(k)",
  property: "房地产",
  vehicles: "车辆",
  otherAssets: "其他资产",
  homeLoan: "房屋贷款",
  vehicleLoan: "汽车贷款",
  cards: "信用卡 / 个人贷款",
  otherDebt: "其他负债",
  monthlyExpenses: "每月生活开销",
  assetTotal: "资产总额",
  debtTotal: "负债总额",
  guideValue: "估值指南",
  assetGuide: "包括银行现金、投资市值、可提取退休储蓄，以及合理的二手转售价值。",
  debtGuide: "填写尚未偿还的本金。如已偿还一部分，请勿填写原始贷款总额。",
  retirementTitle: "退休模拟器",
  retirementHint: "查看何时可以退休，以及退休后资金是否足够。",
  preRetirement: "退休前",
  postRetirement: "退休后",
  preRetirementHint: "我的储蓄足够吗？何时可以退休？",
  postRetirementHint: "每月可以花多少？资金可以维持多久？",
  currentAge: "当前年龄",
  retirementAge: "理想退休年龄",
  retirementAccessAge: "退休金可使用年龄",
  retirementAccessHelp: "锁定退休储蓄可开始使用的年龄，请按你的账户规则填写。",
  planToAge: "规划至年龄",
  currentSavings: "退休资源",
  monthlySavings: "每月个人储蓄",
  annualSavings: "每年个人储蓄",
  monthlyContribution: "每月退休金投入",
  annualRetirementContribution: "每年退休金投入",
  cashReturn: "现金 / 储蓄回报",
  investmentReturn: "投资 + 股息回报",
  retirementReturn: "退休账户回报",
  inflation: "年度通胀",
  monthlySpending: "今日每月开销",
  desiredRetirementSpending: "退休后理想每月开销 — 以今日价值计算",
  maximumMonthlySpending: "最高可持续每月开销",
  useMaximumSpending: "采用最高可持续每月开销",
  monthlyIncome: "其他每月退休收入",
  monthlyIncomeHelp: "租金、养老金、年金、其他。",
  majorWithdrawals: "大额提款与紧急开销",
  majorWithdrawalsHelp: "医疗、装修、购车或意外损失。",
  plannedLargeExpenses: "计划中的大额开销",
  plannedLargeExpensesHelp: "退休前的房产首付、购车、教育或医疗费用。如使用贷款，只填写现金首付、费用或从储蓄支付的金额。",
  preRetirementMonthlyIncome: "退休前每月收入",
  preRetirementMonthlyExpenses: "退休前每月开销",
  retirementContributionSource: "退休金投入来源",
  retirementContributionSourceHelp: "选择投入来源。使用现有储蓄属于资金转移，不是新增财富。",
  contributionSources: ["每月收入", "外部投入", "现有储蓄"],
  availableToSave: "可用于储蓄",
  oneTimeMoneyEvents: "一次性资金事项",
  oneTimeMoneyEventsHelp: "在同一清单中加入出售资产所得、遗产、奖金或其他一次性收入，并安排大额提款。",
  noMoneyEvents: "尚未添加一次性资金事项",
  addMoney: "增加资金",
  withdrawMoney: "提取资金",
  eventAge: "年龄",
  eventMonth: "月份（1–12）",
  netAmountReceived: "实际净收入",
  eventAmount: "金额",
  eventReason: "原因",
  eventDestination: "存入",
  saveMoneyEvent: "保存事项",
  freeMoneyEventLimit: "免费版支持一项一次性资金事项；付费版支持多项。",
  addMoneyReasons: ["出售房产", "出售车辆", "遗产或赠与", "奖金或一次性副业收入", "业务所得", "保险赔付", "其他收入"],
  withdrawMoneyReasons: ["房产首付", "教育费用", "医疗费用", "装修", "购买新车", "家庭支援", "诈骗损失", "其他紧急开销"],
  moneyDestinations: ["现金", "投资", "退休基金"],
  netProceedsNote: "出售房产或车辆时，请填写扣除未偿贷款、费用和税项后的净收入。",
  moneyAdded: "增加资金",
  moneyWithdrawn: "提取资金",
  eventImpact: "一次性资金事项影响",
  withoutEvents: "不含资金事项",
  withEvents: "包含资金事项",
  noMajorWithdrawals: "尚未添加大额提款",
  addWithdrawal: "添加提款",
  withdrawalAge: "提款年龄",
  withdrawalMonth: "生日后的月份",
  withdrawalAmount: "金额",
  withdrawalReason: "原因",
  amountAtFutureAge: "请输入预计在该未来年龄发生的金额。",
  automaticLowestReturn: "自动 — 最低回报优先",
  saveWithdrawal: "保存提款",
  cancel: "取消",
  withdrawalEdit: "编辑",
  withdrawalRemove: "删除",
  freeWithdrawalLimit: "免费版支持一项大额提款；付费版支持多项提款。",
  withdrawalReasons: ["医疗费用", "房屋装修", "购买新车", "诈骗损失", "家庭支援", "其他紧急开销", "房产首付", "教育费用"],
  beforeWithdrawal: "提款前",
  afterWithdrawal: "提款后",
  withdrawalImpact: "提款影响",
  unfundedExpense: "未获资金的大额开销",
  useMyBalance: "使用我的现金 + 投资 + 退休数据",
  projectedFund: "退休时预计资金",
  projectedAccessibleFund: "退休时可用资金",
  projectedLockedFund: "锁定至可使用年龄",
  requiredFund: "估计所需资金",
  targetRetirementSum: "目标退休资金",
  fundingGap: "资金缺口 / 盈余",
  earliestRetirementAge: "最早可退休年龄",
  financiallyIndependentNow: "你可能现在就能退休",
  mayRetireAt: "你最早可能在此年龄退休",
  notYetAchievable: "按目前数据尚未能实现",
  bridgePeriod: "提早退休过渡期",
  bridgePeriodHelp: "可用储蓄必须支持生活，直至锁定退休金可以使用。",
  increaseSavingsBy: "每月增加储蓄",
  requiredMonthlySavings: "每月所需个人储蓄",
  yearlyTargets: "年度储蓄目标",
  yearlyTargetsHint: "比较预计余额与保持计划所需的目标。",
  targetBalance: "目标余额",
  accessibleBalance: "可用余额",
  lockedBalance: "锁定退休金",
  projectedBalance: "预计余额",
  advancedSettings: "进阶假设",
  lastsUntil: "资金预计维持至",
  fundsMayRunOutAt: "资金可能在此年龄耗尽",
  remainingFundAtAge: "此年龄的剩余资金",
  fundsSupportThroughAge: "资金可支持至年龄",
  age: "年龄",
  onTrack: "计划达标",
  needsWork: "计划需要调整",
  monthlySavingNeeded: "估计每月所需储蓄",
  firstYearSpend: "退休首年开销",
  projection: "资金预测",
  projectionNote: "仅供说明。回报与通胀会变化；模拟未包括税务或投资费用。",
  assumptions: "假设",
  scenariosTitle: "探索示例路径",
  scenariosHint: "载入示例，再按你的实际财务状况调整。",
  loadScenario: "使用此示例",
  scenarioNames: ["均衡 RM500k", "财富起步", "财富增长", "财务自由", "资不抵债警示"],
  scenarioDescs: ["64% 净资产基础", "建立流动性并减少债务", "资产增长快于债务", "高现金保障且无负债", "负债超过全部资产"],
  profilePage: "个人资料",
  profileTitle: "你的资料",
  profileHint: "只需填写一次基本资料。年龄会根据出生日期自动更新。",
  fullName: "姓名",
  dateOfBirth: "出生日期",
  calculatedAge: "当前年龄",
  sex: "性别",
  profession: "职业",
  sexChoose: "请选择",
  sexMale: "男",
  sexFemale: "女",
  sexPreferNot: "不愿透露",
  profileSaved: "个人资料保存在此设备",
  editProfile: "我的资料",
  liabilitiesDetails: "负债明细",
  wealthReport: "财富报告",
  professionLabel: "职业",
  asAt: "截至",
  reportTitle: "你的财务报告",
  reportHint: "保存私人快照，或分享给你信任的人。",
  upgradeTitle: "解锁完整退休报告",
  upgradeMessage: "升级至付费版，添加多项大额提款、自定义回报假设并查看完整年度摘要。",
  unlockFullVersion: "解锁完整版",
  restorePurchase: "恢复购买",
  billingConnecting: "正在连接 Google Play…",
  billingUnavailable: "Google Play 购买目前不可用。请从 Google Play 安装或更新应用后重试。",
  purchaseRestored: "完整版已恢复。",
  purchaseCancelled: "购买已取消。",
  purchasePending: "付款正在处理中。Google 确认后将解锁完整版。",
  noPurchaseFound: "此 Google 账号没有找到之前的完整版购买记录。",
  paidEdition: "付费版",
  close: "关闭",
  conservativeAssumption: "保守 2.5% 假设",
  customizeReturns: "升级付费版可自定义回报假设。",
  quarterlyProgress: "季度进度",
  quarterlyProgressHint: "每季度保存一次记录，追踪资产、负债和净资产。",
  saveQuarter: "保存本季度",
  progressLimitFree: "免费版最多保存 2 个季度记录。",
  progressLimitPaid: "付费版最多保存 40 个季度记录（10 年）。",
  snapshotSaved: "季度已保存",
  noSnapshots: "尚无季度记录。",
  retirementYearlySummary: "退休后年度摘要",
  freeYearlyLimit: "免费报告显示退休后的首 5 年；付费版显示完整年度摘要。",
  freePreYearlyLimit: "免费报告显示退休前首 5 年；付费版显示全部年度目标。",
  paidYearlyLimit: "显示至所选最终年龄的完整年度摘要。",
  openingBalance: "期初余额",
  cashBalance: "年末现金余额",
  investmentBalance: "年末投资 + 股息余额",
  retirementBalance: "年末退休金余额",
  yearlySpending: "年度开销",
  otherMonthlyIncome: "其他每月收入",
  otherYearlyIncome: "其他年度收入",
  totalReturn: "总回报",
  endingBalance: "年末余额",
  exportPdf: "导出 PDF",
  shareReport: "分享报告",
  exporting: "正在生成报告…",
  pdfReady: "PDF 已下载",
  shared: "报告已分享",
  shareUnavailable: "无法直接分享，PDF 已改为下载。",
  privacyPolicy: "隐私政策",
  reportPrivacy: "报告在你的设备上生成。个人资产负债方格不会上传任何数据。",
  reset: "重置所有数据",
  resetConfirm: "把资产负债表与退休模拟器恢复为原始示例？",
  strong: "稳健",
  moderate: "适中",
  attention: "需要关注",
  debtFree: "无负债",
  custom: "自定义数据",
  currency: "货币",
};

export const translations = { en, ms: { ...en, ...ms }, zh: { ...en, ...zh } };
