export const assetKeys = ["cash", "investments", "retirement", "property", "vehicles", "otherAssets"];
export const debtKeys = ["homeLoan", "vehicleLoan", "cards", "otherDebt"];

export const defaultValues = {
  cash: 40000,
  investments: 90000,
  retirement: 120000,
  property: 220000,
  vehicles: 25000,
  otherAssets: 5000,
  homeLoan: 120000,
  vehicleLoan: 40000,
  cards: 5000,
  otherDebt: 15000,
  monthlyExpenses: 5000,
};

export const defaultRetirement = {
  currentAge: 53,
  retirementAge: 60,
  planToAge: 90,
  currentSavings: 250000,
  monthlyContribution: 3000,
  returnBefore: 5.5,
  returnAfter: 4.5,
  inflation: 2.75,
  monthlySpending: 6000,
  monthlyIncome: 1500,
};

export const scenarios = [
  {
    id: "balanced",
    values: { ...defaultValues },
  },
  {
    id: "starting",
    values: { cash: 18000, investments: 12000, retirement: 45000, property: 0, vehicles: 30000, otherAssets: 5000, homeLoan: 0, vehicleLoan: 50000, cards: 9000, otherDebt: 16000, monthlyExpenses: 3500 },
  },
  {
    id: "growing",
    values: { cash: 120000, investments: 280000, retirement: 310000, property: 420000, vehicles: 50000, otherAssets: 20000, homeLoan: 230000, vehicleLoan: 35000, cards: 0, otherDebt: 0, monthlyExpenses: 6500 },
  },
  {
    id: "freedom",
    values: { cash: 360000, investments: 1050000, retirement: 780000, property: 650000, vehicles: 100000, otherAssets: 60000, homeLoan: 0, vehicleLoan: 0, cards: 0, otherDebt: 0, monthlyExpenses: 8000 },
  },
  {
    id: "insolvent",
    values: { cash: 5000, investments: 10000, retirement: 25000, property: 0, vehicles: 15000, otherAssets: 5000, homeLoan: 0, vehicleLoan: 60000, cards: 25000, otherDebt: 15000, monthlyExpenses: 3000 },
  },
];

const en = {
  brand: "Balance Sheet Square",
  shortBrand: "BSS",
  eyebrow: "PERSONAL WEALTH BLUEPRINT",
  titleA: "See your wealth.",
  titleB: "Shape your freedom.",
  intro: "One clear place to understand what you own, what you owe, and whether your retirement plan is on track.",
  local: "Your figures stay on this device",
  offline: "Works offline",
  saved: "Saved automatically",
  home: "Home",
  square: "My Square",
  assetsPage: "Assets",
  debtsPage: "Debts",
  retirePage: "Retirement",
  scenariosPage: "Examples",
  reportPage: "Report",
  overview: "Financial overview",
  overviewHint: "Your latest figures at a glance.",
  netWorth: "Net worth",
  totalAssets: "Total assets",
  liabilities: "Liabilities",
  equity: "Equity",
  debtAsset: "Debt-to-assets",
  equityRatio: "Equity ratio",
  debtEquity: "Debt-to-equity",
  runway: "Cash runway",
  months: "months",
  perMonth: "per month",
  next: "Next",
  back: "Back",
  open: "Open",
  edit: "Edit",
  startSquare: "Build my financial square",
  planRetirement: "Plan my retirement",
  quickActions: "Choose what to work on",
  quickHint: "Each section is now a focused page with larger controls and clearer results.",
  squareTitle: "Your financial square",
  squareHint: "The left side is what you own. The right side shows debt and the wealth that belongs to you.",
  equation: "Assets = Liabilities + Equity",
  balanced: "Balanced",
  insolvent: "Insolvent / bankruptcy risk",
  bankruptcyNote: "Your liabilities exceed your assets. This is a serious warning; legal bankruptcy depends on formal proceedings.",
  liabilitiesExceed: "Liabilities exceed assets by",
  assetMix: "Asset mix",
  assetsTitle: "Enter your assets",
  assetsHint: "Use realistic current values, not original purchase prices.",
  debtsTitle: "Enter your liabilities",
  debtsHint: "Use the latest outstanding balances for every debt.",
  cash: "Cash & savings",
  investments: "Investments",
  retirement: "Retirement / KWSP",
  property: "Property",
  vehicles: "Vehicles",
  otherAssets: "Other assets",
  homeLoan: "Home loan",
  vehicleLoan: "Vehicle loan",
  cards: "Credit cards / personal loans",
  otherDebt: "Other liabilities",
  monthlyExpenses: "Monthly living expenses",
  assetTotal: "Asset total",
  debtTotal: "Debt total",
  guideValue: "Guide to value",
  assetGuide: "Cash at bank, market value of investments, withdrawable retirement savings, and realistic resale values.",
  debtGuide: "Include principal still owed. Do not enter the original loan amount if part has already been repaid.",
  retirementTitle: "Retirement simulator",
  retirementHint: "Estimate how your fund may grow and how long it could support your lifestyle.",
  currentAge: "Current age",
  retirementAge: "Retire at age",
  planToAge: "Plan until age",
  currentSavings: "Current retirement savings",
  monthlyContribution: "Monthly contribution",
  returnBefore: "Annual return before retirement",
  returnAfter: "Annual return after retirement",
  inflation: "Annual inflation",
  monthlySpending: "Monthly spending today",
  monthlyIncome: "Other monthly retirement income",
  useMyBalance: "Use my investment + KWSP figures",
  projectedFund: "Projected fund at retirement",
  requiredFund: "Estimated fund required",
  fundingGap: "Funding gap / surplus",
  lastsUntil: "Fund lasts until",
  age: "Age",
  onTrack: "On track",
  needsWork: "Plan needs adjustment",
  monthlySavingNeeded: "Estimated monthly saving needed",
  firstYearSpend: "First-year retirement spending",
  projection: "Fund projection",
  projectionNote: "Illustration only. Returns and inflation vary, and the simulator does not include tax or investment fees.",
  assumptions: "Assumptions",
  scenariosTitle: "Explore example paths",
  scenariosHint: "Load an example, then adjust the figures to match your own finances.",
  loadScenario: "Use this example",
  scenarioNames: ["Balanced RM500k", "Starting out", "Growing wealth", "Financial freedom", "Insolvency warning"],
  scenarioDescs: ["A 64% equity base", "Build liquidity and reduce debt", "Assets grow faster than debt", "High runway with no debt", "Liabilities exceed all assets"],
  reportTitle: "Your financial report",
  reportHint: "Save a private snapshot or share it with someone you trust.",
  exportPdf: "Export PDF",
  shareReport: "Share report",
  exporting: "Preparing your report…",
  pdfReady: "PDF downloaded",
  shared: "Report shared",
  shareUnavailable: "Direct sharing is unavailable, so the PDF was downloaded instead.",
  privacyPolicy: "Privacy policy",
  reportPrivacy: "The report is created on your device. Nothing is uploaded by Balance Sheet Square.",
  reset: "Reset all figures",
  resetConfirm: "Reset the balance sheet and retirement simulator to the original example?",
  strong: "Strong",
  moderate: "Moderate",
  attention: "Needs attention",
  debtFree: "Debt-free",
  custom: "Custom figures",
  percentage: "%",
  currency: "Currency",
};

const ms = {
  brand: "Petak Kunci Kira-kira",
  eyebrow: "PELAN INDUK HARTA PERIBADI",
  titleA: "Lihat harta anda.",
  titleB: "Bentuk kebebasan anda.",
  intro: "Satu tempat yang jelas untuk memahami apa yang anda miliki, hutang anda dan sama ada pelan persaraan berada di landasan.",
  local: "Angka anda kekal pada peranti ini",
  offline: "Berfungsi luar talian",
  saved: "Disimpan secara automatik",
  home: "Utama",
  square: "Petak Saya",
  assetsPage: "Aset",
  debtsPage: "Hutang",
  retirePage: "Persaraan",
  scenariosPage: "Contoh",
  reportPage: "Laporan",
  overview: "Gambaran kewangan",
  overviewHint: "Angka terkini anda sepintas lalu.",
  netWorth: "Nilai bersih",
  totalAssets: "Jumlah aset",
  liabilities: "Liabiliti",
  equity: "Ekuiti",
  debtAsset: "Hutang kepada aset",
  equityRatio: "Nisbah ekuiti",
  debtEquity: "Hutang kepada ekuiti",
  runway: "Tempoh tunai",
  months: "bulan",
  perMonth: "sebulan",
  next: "Seterusnya",
  back: "Kembali",
  open: "Buka",
  edit: "Ubah",
  startSquare: "Bina petak kewangan saya",
  planRetirement: "Rancang persaraan saya",
  quickActions: "Pilih perkara untuk diurus",
  quickHint: "Setiap bahagian kini mempunyai halaman fokus, kawalan lebih besar dan keputusan lebih jelas.",
  squareTitle: "Petak kewangan anda",
  squareHint: "Bahagian kiri ialah apa yang anda miliki. Bahagian kanan menunjukkan hutang dan harta milik anda.",
  equation: "Aset = Liabiliti + Ekuiti",
  balanced: "Seimbang",
  insolvent: "Tidak solven / risiko muflis",
  bankruptcyNote: "Liabiliti melebihi aset. Ini amaran serius; status muflis bergantung pada proses undang-undang rasmi.",
  liabilitiesExceed: "Liabiliti melebihi aset sebanyak",
  assetMix: "Campuran aset",
  assetsTitle: "Masukkan aset anda",
  assetsHint: "Gunakan nilai semasa yang realistik, bukan harga belian asal.",
  debtsTitle: "Masukkan liabiliti anda",
  debtsHint: "Gunakan baki terkini bagi setiap hutang.",
  cash: "Tunai & simpanan",
  investments: "Pelaburan",
  retirement: "Persaraan / KWSP",
  property: "Hartanah",
  vehicles: "Kenderaan",
  otherAssets: "Aset lain",
  homeLoan: "Pinjaman rumah",
  vehicleLoan: "Pinjaman kenderaan",
  cards: "Kad kredit / pinjaman peribadi",
  otherDebt: "Liabiliti lain",
  monthlyExpenses: "Perbelanjaan hidup bulanan",
  assetTotal: "Jumlah aset",
  debtTotal: "Jumlah hutang",
  guideValue: "Panduan nilai",
  assetGuide: "Tunai di bank, nilai pasaran pelaburan, simpanan persaraan yang boleh dikeluarkan dan nilai jualan semula yang realistik.",
  debtGuide: "Masukkan prinsipal yang masih terhutang. Jangan gunakan jumlah pinjaman asal jika sebahagiannya telah dibayar.",
  retirementTitle: "Simulator persaraan",
  retirementHint: "Anggarkan pertumbuhan dana dan tempoh ia dapat menyokong gaya hidup anda.",
  currentAge: "Umur semasa",
  retirementAge: "Bersara pada umur",
  planToAge: "Rancang sehingga umur",
  currentSavings: "Simpanan persaraan semasa",
  monthlyContribution: "Caruman bulanan",
  returnBefore: "Pulangan tahunan sebelum bersara",
  returnAfter: "Pulangan tahunan selepas bersara",
  inflation: "Inflasi tahunan",
  monthlySpending: "Perbelanjaan bulanan hari ini",
  monthlyIncome: "Pendapatan persaraan bulanan lain",
  useMyBalance: "Guna angka pelaburan + KWSP saya",
  projectedFund: "Dana dijangka ketika bersara",
  requiredFund: "Anggaran dana diperlukan",
  fundingGap: "Kekurangan / lebihan dana",
  lastsUntil: "Dana bertahan sehingga",
  age: "Umur",
  onTrack: "Di landasan",
  needsWork: "Pelan perlu dilaras",
  monthlySavingNeeded: "Anggaran simpanan bulanan diperlukan",
  firstYearSpend: "Perbelanjaan tahun pertama persaraan",
  projection: "Unjuran dana",
  projectionNote: "Ilustrasi sahaja. Pulangan dan inflasi berubah, dan simulasi tidak termasuk cukai atau yuran pelaburan.",
  assumptions: "Andaian",
  scenariosTitle: "Terokai contoh laluan",
  scenariosHint: "Muatkan contoh, kemudian laraskan mengikut kewangan anda.",
  loadScenario: "Guna contoh ini",
  scenarioNames: ["Seimbang RM500k", "Permulaan", "Harta berkembang", "Kebebasan kewangan", "Amaran tidak solven"],
  scenarioDescs: ["Asas ekuiti 64%", "Bina kecairan dan kurangkan hutang", "Aset berkembang lebih pantas", "Tempoh tunai tinggi tanpa hutang", "Liabiliti melebihi semua aset"],
  reportTitle: "Laporan kewangan anda",
  reportHint: "Simpan rekod peribadi atau kongsi dengan individu yang anda percayai.",
  exportPdf: "Eksport PDF",
  shareReport: "Kongsi laporan",
  exporting: "Menyediakan laporan anda…",
  pdfReady: "PDF telah dimuat turun",
  shared: "Laporan telah dikongsi",
  shareUnavailable: "Perkongsian terus tidak tersedia, jadi PDF telah dimuat turun.",
  privacyPolicy: "Dasar privasi",
  reportPrivacy: "Laporan dicipta pada peranti anda. Tiada data dimuat naik oleh Petak Kunci Kira-kira.",
  reset: "Tetapkan semula semua angka",
  resetConfirm: "Tetapkan semula petak kewangan dan simulator persaraan kepada contoh asal?",
  strong: "Kukuh",
  moderate: "Sederhana",
  attention: "Perlu perhatian",
  debtFree: "Bebas hutang",
  custom: "Angka tersuai",
  currency: "Mata wang",
};

const zh = {
  brand: "个人资产负债方格",
  eyebrow: "个人财富蓝图",
  titleA: "看见你的财富。",
  titleB: "塑造你的自由。",
  intro: "在一个清晰的空间里，了解你拥有多少、负债多少，以及退休计划是否在正确轨道上。",
  local: "你的数据只保留在此设备",
  offline: "可离线使用",
  saved: "自动保存",
  home: "主页",
  square: "我的方格",
  assetsPage: "资产",
  debtsPage: "负债",
  retirePage: "退休",
  scenariosPage: "示例",
  reportPage: "报告",
  overview: "财务概览",
  overviewHint: "快速查看你的最新数据。",
  netWorth: "净资产",
  totalAssets: "总资产",
  liabilities: "负债",
  equity: "净资产",
  debtAsset: "负债资产比",
  equityRatio: "净资产比率",
  debtEquity: "负债净资产比",
  runway: "现金可用期",
  months: "个月",
  perMonth: "每月",
  next: "下一步",
  back: "返回",
  open: "打开",
  edit: "修改",
  startSquare: "建立我的财务方格",
  planRetirement: "规划我的退休",
  quickActions: "选择要处理的项目",
  quickHint: "每个部分现在都有独立页面、更大的控件和更清晰的结果。",
  squareTitle: "你的财务方格",
  squareHint: "左边是你拥有的资产；右边显示负债和真正属于你的财富。",
  equation: "资产 = 负债 + 净资产",
  balanced: "平衡",
  insolvent: "资不抵债 / 破产风险",
  bankruptcyNote: "负债已超过资产。这是严重警讯；法律上的破产须经正式程序确定。",
  liabilitiesExceed: "负债超出资产",
  assetMix: "资产组合",
  assetsTitle: "输入你的资产",
  assetsHint: "使用合理的当前价值，而不是原始买入价。",
  debtsTitle: "输入你的负债",
  debtsHint: "使用每项债务最新的未偿余额。",
  cash: "现金与储蓄",
  investments: "投资",
  retirement: "退休金 / 公积金",
  property: "房地产",
  vehicles: "车辆",
  otherAssets: "其他资产",
  homeLoan: "房屋贷款",
  vehicleLoan: "汽车贷款",
  cards: "信用卡 / 个人贷款",
  otherDebt: "其他负债",
  monthlyExpenses: "每月生活开销",
  assetTotal: "资产总额",
  debtTotal: "负债总额",
  guideValue: "估值指南",
  assetGuide: "包括银行现金、投资市值、可提取退休储蓄，以及合理的二手转售价值。",
  debtGuide: "填写尚未偿还的本金。如已偿还一部分，请勿填写原始贷款总额。",
  retirementTitle: "退休模拟器",
  retirementHint: "估算资金如何增长，以及可支持生活多久。",
  currentAge: "当前年龄",
  retirementAge: "退休年龄",
  planToAge: "规划至年龄",
  currentSavings: "当前退休储蓄",
  monthlyContribution: "每月投入",
  returnBefore: "退休前年度回报",
  returnAfter: "退休后年度回报",
  inflation: "年度通胀",
  monthlySpending: "今日每月开销",
  monthlyIncome: "其他每月退休收入",
  useMyBalance: "使用我的投资 + 公积金数据",
  projectedFund: "退休时预计资金",
  requiredFund: "估计所需资金",
  fundingGap: "资金缺口 / 盈余",
  lastsUntil: "资金预计维持至",
  age: "年龄",
  onTrack: "计划达标",
  needsWork: "计划需要调整",
  monthlySavingNeeded: "估计每月所需储蓄",
  firstYearSpend: "退休首年开销",
  projection: "资金预测",
  projectionNote: "仅供说明。回报与通胀会变化；模拟未包括税务或投资费用。",
  assumptions: "假设",
  scenariosTitle: "探索示例路径",
  scenariosHint: "载入示例，再按你的实际财务状况调整。",
  loadScenario: "使用此示例",
  scenarioNames: ["均衡 RM500k", "财富起步", "财富增长", "财务自由", "资不抵债警示"],
  scenarioDescs: ["64% 净资产基础", "建立流动性并减少债务", "资产增长快于债务", "高现金保障且无负债", "负债超过全部资产"],
  reportTitle: "你的财务报告",
  reportHint: "保存私人快照，或分享给你信任的人。",
  exportPdf: "导出 PDF",
  shareReport: "分享报告",
  exporting: "正在生成报告…",
  pdfReady: "PDF 已下载",
  shared: "报告已分享",
  shareUnavailable: "无法直接分享，PDF 已改为下载。",
  privacyPolicy: "隐私政策",
  reportPrivacy: "报告在你的设备上生成。个人资产负债方格不会上传任何数据。",
  reset: "重置所有数据",
  resetConfirm: "把资产负债表与退休模拟器恢复为原始示例？",
  strong: "稳健",
  moderate: "适中",
  attention: "需要关注",
  debtFree: "无负债",
  custom: "自定义数据",
  currency: "货币",
};

export const translations = { en, ms: { ...en, ...ms }, zh: { ...en, ...zh } };
